import { chromium } from 'playwright';
const base='https://school.0com.my';
const id='diag'+Date.now().toString(36).slice(-8);
const pin='583214';
const b=await chromium.launch({headless:true});
const c=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});
const p=await c.newPage();
p.on('console',m=>console.log('BROWSER',m.type(),m.text()));
p.on('pageerror',e=>console.log('PAGEERROR',String(e)));
p.on('response',async r=>{if(r.url().includes('/api/')){let body='';try{body=(await r.text()).slice(0,1000)}catch{};console.log('API',r.status(),r.request().method(),new URL(r.url()).pathname,body)}});
await p.goto(base,{waitUntil:'networkidle'});
await p.locator('#regName').fill('Quiz Diagnostic');
await p.locator('#regStudentId').fill(id);
await p.locator('#regPin').fill(pin);
await p.locator('#regIdStatus.success').waitFor({timeout:10000});
await p.locator('#regSubmit').click();
await p.locator('#studentApp:not(.hidden)').waitFor({state:'visible',timeout:15000});
await p.locator('.nav button[data-screen="learn"]').click();
await p.locator('#learningModules button').first().click();
const q=await p.evaluate(()=>({subject:eval('currentQuiz.subject'),q:eval('currentQuiz.q'),task:eval('currentTask')}));
console.log('CURRENT',JSON.stringify(q));
const quizResponse=p.waitForResponse(r=>new URL(r.url()).pathname==='/api/student/quiz',{timeout:15000}).catch(e=>null);
await p.locator('#answers button').nth(q.q.c).click();
const qr=await quizResponse;
console.log('QUIZ_RESPONSE_SEEN',!!qr,qr?.status());
const progressResponse=await p.waitForResponse(r=>new URL(r.url()).pathname==='/api/student/progress',{timeout:10000}).catch(e=>null);
console.log('PROGRESS_RESPONSE_SEEN',!!progressResponse,progressResponse?.status());
await p.waitForTimeout(3500);
console.log('TOAST',await p.locator('#toast').textContent(),await p.locator('#toast').getAttribute('class'));
console.log('AFTER',JSON.stringify(await p.evaluate(()=>({answered:eval('currentQuiz.answered'),stats:eval('state.stats'),progress:eval('state.progress').filter(x=>Number(x.day_no)===1)}))));
await p.screenshot({path:'diag-answer.png',fullPage:true});
await b.close();
if(!qr)process.exit(2);
